name: autosign_cron

on:
    schedule:
      - cron:  '1 16 * * *'
      - cron:  '1 3 * * *'
      - cron:  '1 14 * * *'
       
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: 16

    - name: Set up Python 3
      uses: actions/setup-python@main
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python3 autosign.py
    
