name: autosign_text

on:
  workflow_dispatch:
       
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Setup Node.js environment
      uses: actions/setup-node@main
      with:
        node-version: 20

    - name: Set up Python 3
      uses: actions/setup-python@main
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script
      run: python3 autosign.py
    
